### ISSUE TITLE
Change translation component from glossary to regluar translation

### ISSUE THREAD

**Issue by comradekingu** [juanro49/autu-mandu#1]
Having it listed as a glossary makes translation harder.
It can be changed in https://hosted.weblate.org/settings/autu-mandu/autu-mandu/ I think.

**Comment by juanro49** [comment]
> Having it listed as a glossary makes translation harder. It can be changed in https://hosted.weblate.org/settings/autu-mandu/autu-mandu/ I think.

Thanks! i changed it!
