### ISSUE TITLE
Layout broken when adding expense

### ISSUE THREAD

**Issue by pitaj** [juanro49/autu-mandu#12]
![Screenshot_20241120-204355.png](https://github.com/user-attachments/assets/c2c2e643-c8e7-45d9-9e3b-8dee800690b7)

Also in any settings page

![Screenshot_20241120-204640.png](https://github.com/user-attachments/assets/3f67f148-c076-43ce-a8b7-353fbf753e6d)

4.0.3 from IzzyOnDroid repository
Pixel 8a
Android 15

**Comment by juanro49** [comment]
Thanks for reporting it, as soon as I have some time I will try to find out the cause.

**Comment by petrblaho** [comment]
Unfortunately the app is unusable as the first field can't be reached out on the phone (I have the same HW and OS version as original reporter) not even in landscape mode ☹️

**Comment by pitaj** [comment]
Seems to be working now! Thank you for the quick fix 😁
