### ISSUE TITLE
Backup & Restore not working

### ISSUE THREAD

**Issue by citizenserious** [juanro49/autu-mandu#2]
In Car Report it works but not in Autu Mandu.

**Comment by juanro49** [comment]
> In Car Report it works but not in Autu Mandu.

Yes, it is a known bug that I have to solve when I have some time. I think it's because of a change in the permissions management when using the latest versions of android for compilation.

**Comment by juanro49** [comment]
Fixed with https://github.com/juanro49/autu-mandu/commit/76a3513620ad38f486cc28724720117487060c9b

New version in few days

**Comment by citizenserious** [comment]
That was in light speed, thank you a lot 🚀

**Comment by enboig** [comment]
Restore from Car Report worked for me, but backup fails.
I am using version 4.0
