### ISSUE TITLE
Suspended cars still show as an option

### ISSUE THREAD

**Issue by infinitytec** [juanro49/autu-mandu#9]
As of at least v. 4.0.2, suspended vehicles still appear as options for vehicles for refilling and other expenses.

This appears to be a regression from Car Report which suspended vehicles as expected.

**Comment by juanro49** [comment]
> As of at least v. 4.0.2, suspended vehicles still appear as options for vehicles for refilling and other expenses.
> 
> This appears to be a regression from Car Report which suspended vehicles as expected.

Thanks for the report, I will look into it as soon as I can spare some time
